### ISSUE TITLE
Data analysis questions to answer

### ISSUE THREAD

**Issue by TomBrown4444** [TomBrown4444/TomBrown4444.github.io#2]
From what date is the PM2.5 emisisons data measured?

How frequently is the data updated/posted?

How current is the data? Can we get more recent data from the mointors if needed?

If we take a SensorFlow device to counties in Texas where there are no air pollution monitors, can we compare the data we gather directly to that compiled in the Choking Texas map? Will the comparison be like-for-like?

Is it possible to view emissions from power stations from 22nd to the 25th of December 2022?

How long will it take to compare PM2.5 to schools and/or population sensors?

Can we see if PM2.5 levels are linked to spikes in flaring from VIIRS?

**Comment by ChristinaLast** [comment]
**From what date is the PM2.5 emissions data measured?**

Different dates for different sensors, see the dashboard with the differnet continuous monitoring stations (ranges from 16-years to 3 years). Our flaring data is from 2018 (october), so this seems like the more important time limit.

**How frequently is the data updated/posted?**

Again, depends on sensor (e.g. continuous or non-continuous monitor). We use OpenAq to get data, this is scraped daily but contains sub-daily levels (e.g. hrly).

**How current is the data? Can we get more recent data from the mointors if needed?**

^this seems like a repeat question

**If we take a SensorFlow device to counties in Texas where there are no air pollution monitors, can we compare the data we gather directly to that compiled in the Choking Texas map? Will the comparison be like-for-like?**

What is a Sensorflow?
We can do fenceline monitoring but Chevron and companies have armies of analysts ready to take on people who do this. We do not have regulation grade monitors so we cant prove anything.

**Is it possible to view emissions from power stations from 22nd to the 25th of December 2022?**

Not directly from stations, again, we can estimate using the continuous monitoring stations and extrapolate (e.g. use ML to predict in new locations using our models). but this is just an estimate. 

**How long will it take to compare PM2.5 to schools and/or population sensors?**
 We arent comparing PM2.5 to schools, we can describe the exposure of schools to PM2.5 using the current monitors, and we an make predictsion + take our sensors to validate our predictions.

What do you mean compare?

**Can we see if PM2.5 levels are linked to spikes in flaring from VIIRS?**

We can try this! we can look over all texas, but i am aware that the flaring data we are using is v. sensitive and we make a lot of assumptions about flaring locations when we do this. Id be keen to find another data source/or develop our own model but not sure how.

**Comment by ChristinaLast** [comment]
https://docs.google.com/document/d/1K71-xyuOCi0-HgWv0PNc5Ov5_UFs1G958fCDDDwQp2I/edit?usp=sharing

Link to interview with Arthur (guy who wrote NO2 guidance for EPA)
